language: cpp
compiler: g++

before_install:
  # CMake
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq
  - sudo apt-get install cmake
  # g++ 4.8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # g++4.8
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  
before_script: cmake CMakeLists.txt

script:
  - $CXX --version
  - make
  
notifications:
  email:
    recipients: swang927@gmail.com
    on_success: change
    on_failure: always
